language: php
dist: trusty
php: 7.3

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - openssl aes-256-cbc -K $encrypted_b9929ad0dae9_key -iv $encrypted_b9929ad0dae9_iv -in encrypt.tar.gz.enc -out encrypt.tar.gz -d

install:
  #Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script: 
  - docker build -t figonzal/udelvd-api:0.2 -f api.DockerFile . 
  - docker build -t figonzal/http-proxy:0.2 -f proxy.DockerFile .
  - docker build -t figonzal/mysql:0.2 -f mysql.DockerFile .
  - docker create network RED_UDELVD
  - docker run --name udelvd-api-test -p 80:80 --network RED_UDELVD figonzal/udelvd-api:0.2
  - docker run --name owasp --network RED_UDELVD -t owasp/zap2docker-weekly zap-full-scan.py -t http://udelvd-api-test/
  - sleep 15

after_success:
  - docker push figonzal/udelvd-api:0.2
  - docker push figonzal/http-proxy:0.2
  - docker push figonzal/mysql:0.2
  
